export const currencyMeta = {
  "AED": { currency: "UAE Dirham", country: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg" },
  "AFN": { currency: "Afghan Afghani", country: "Afghanistan", flag: "https://flagcdn.com/af.svg" },
  "ALL": { currency: "Albanian Lek", country: "Albania", flag: "https://flagcdn.com/al.svg" },
  "AMD": { currency: "Armenian Dram", country: "Armenia", flag: "https://flagcdn.com/am.svg" },
  "ANG": { currency: "Netherlands Antillian Guilder", country: "Netherlands Antilles", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/No_flag.svg/2560px-No_flag.svg.png" }, // Aruba sebagai pengganti
  "AOA": { currency: "Angolan Kwanza", country: "Angola", flag: "https://flagcdn.com/ao.svg" },
  "ARS": { currency: "Argentine Peso", country: "Argentina", flag: "https://flagcdn.com/ar.svg" },
  "AUD": { currency: "Australian Dollar", country: "Australia", flag: "https://flagcdn.com/au.svg" },
  "AWG": { currency: "Aruban Florin", country: "Aruba", flag: "https://flagcdn.com/aw.svg" },
  "AZN": { currency: "Azerbaijani Manat", country: "Azerbaijan", flag: "https://flagcdn.com/az.svg" },
  "BAM": { currency: "Bosnia and Herzegovina Mark", country: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg" },
  "BBD": { currency: "Barbados Dollar", country: "Barbados", flag: "https://flagcdn.com/bb.svg" },
  "BDT": { currency: "Bangladeshi Taka", country: "Bangladesh", flag: "https://flagcdn.com/bd.svg" },
  "BGN": { currency: "Bulgarian Lev", country: "Bulgaria", flag: "https://flagcdn.com/bg.svg" },
  "BHD": { currency: "Bahraini Dinar", country: "Bahrain", flag: "https://flagcdn.com/bh.svg" },
  "BIF": { currency: "Burundian Franc", country: "Burundi", flag: "https://flagcdn.com/bi.svg" },
  "BMD": { currency: "Bermudian Dollar", country: "Bermuda", flag: "https://flagcdn.com/bm.svg" },
  "BND": { currency: "Brunei Dollar", country: "Brunei", flag: "https://flagcdn.com/bn.svg" },
  "BOB": { currency: "Bolivian Boliviano", country: "Bolivia", flag: "https://flagcdn.com/bo.svg" },
  "BRL": { currency: "Brazilian Real", country: "Brazil", flag: "https://flagcdn.com/br.svg" },
  "BSD": { currency: "Bahamian Dollar", country: "Bahamas", flag: "https://flagcdn.com/bs.svg" },
  "BTN": { currency: "Bhutanese Ngultrum", country: "Bhutan", flag: "https://flagcdn.com/bt.svg" },
  "BWP": { currency: "Botswana Pula", country: "Botswana", flag: "https://flagcdn.com/bw.svg" },
  "BYN": { currency: "Belarusian Ruble", country: "Belarus", flag: "https://flagcdn.com/by.svg" },
  "BZD": { currency: "Belize Dollar", country: "Belize", flag: "https://flagcdn.com/bz.svg" },
  "CAD": { currency: "Canadian Dollar", country: "Canada", flag: "https://flagcdn.com/ca.svg" },
  "CDF": { currency: "Congolese Franc", country: "Democratic Republic of the Congo", flag: "https://flagcdn.com/cd.svg" },
  "CHF": { currency: "Swiss Franc", country: "Switzerland", flag: "https://flagcdn.com/ch.svg" },
  "CLP": { currency: "Chilean Peso", country: "Chile", flag: "https://flagcdn.com/cl.svg" },
  "CNY": { currency: "Chinese Renminbi", country: "China", flag: "https://flagcdn.com/cn.svg" },
  "COP": { currency: "Colombian Peso", country: "Colombia", flag: "https://flagcdn.com/co.svg" },
  "CRC": { currency: "Costa Rican Colon", country: "Costa Rica", flag: "https://flagcdn.com/cr.svg" },
  "CUP": { currency: "Cuban Peso", country: "Cuba", flag: "https://flagcdn.com/cu.svg" },
  "CVE": { currency: "Cape Verdean Escudo", country: "Cape Verde", flag: "https://flagcdn.com/cv.svg" },
  "CZK": { currency: "Czech Koruna", country: "Czech Republic", flag: "https://flagcdn.com/cz.svg" },
  "DJF": { currency: "Djiboutian Franc", country: "Djibouti", flag: "https://flagcdn.com/dj.svg" },
  "DKK": { currency: "Danish Krone", country: "Denmark", flag: "https://flagcdn.com/dk.svg" },
  "DOP": { currency: "Dominican Peso", country: "Dominican Republic", flag: "https://flagcdn.com/do.svg" },
  "DZD": { currency: "Algerian Dinar", country: "Algeria", flag: "https://flagcdn.com/dz.svg" },
  "EGP": { currency: "Egyptian Pound", country: "Egypt", flag: "https://flagcdn.com/eg.svg" },
  "ERN": { currency: "Eritrean Nakfa", country: "Eritrea", flag: "https://flagcdn.com/er.svg" },
  "ETB": { currency: "Ethiopian Birr", country: "Ethiopia", flag: "https://flagcdn.com/et.svg" },
  "EUR": { currency: "Euro", country: "European Union", flag: "https://flagcdn.com/eu.svg" },
  "FJD": { currency: "Fiji Dollar", country: "Fiji", flag: "https://flagcdn.com/fj.svg" },
  "FKP": { currency: "Falkland Islands Pound", country: "Falkland Islands", flag: "https://flagcdn.com/fk.svg" },
  "FOK": { currency: "Faroese Króna", country: "Faroe Islands", flag: "https://flagcdn.com/fo.svg" },
  "GBP": { currency: "Pound Sterling", country: "United Kingdom", flag: "https://flagcdn.com/gb.svg" },
  "GEL": { currency: "Georgian Lari", country: "Georgia", flag: "https://flagcdn.com/ge.svg" },
  "GGP": { currency: "Guernsey Pound", country: "Guernsey", flag: "https://flagcdn.com/gg.svg" },
  "GHS": { currency: "Ghanaian Cedi", country: "Ghana", flag: "https://flagcdn.com/gh.svg" },
  "GIP": { currency: "Gibraltar Pound", country: "Gibraltar", flag: "https://flagcdn.com/gi.svg" },
  "GMD": { currency: "Gambian Dalasi", country: "The Gambia", flag: "https://flagcdn.com/gm.svg" },
  "GNF": { currency: "Guinean Franc", country: "Guinea", flag: "https://flagcdn.com/gn.svg" },
  "GTQ": { currency: "Guatemalan Quetzal", country: "Guatemala", flag: "https://flagcdn.com/gt.svg" },
  "GYD": { currency: "Guyanese Dollar", country: "Guyana", flag: "https://flagcdn.com/gy.svg" },
  "HKD": { currency: "Hong Kong Dollar", country: "Hong Kong", flag: "https://flagcdn.com/hk.svg" },
  "HNL": { currency: "Honduran Lempira", country: "Honduras", flag: "https://flagcdn.com/hn.svg" },
  "HRK": { currency: "Croatian Kuna", country: "Croatia", flag: "https://flagcdn.com/hr.svg" },
  "HTG": { currency: "Haitian Gourde", country: "Haiti", flag: "https://flagcdn.com/ht.svg" },
  "HUF": { currency: "Hungarian Forint", country: "Hungary", flag: "https://flagcdn.com/hu.svg" },
  "IDR": { currency: "Indonesian Rupiah", country: "Indonesia", flag: "https://flagcdn.com/id.svg" },
  "ILS": { currency: "Israeli New Shekel", country: "Israel", flag: "https://flagcdn.com/il.svg" },
  "IMP": { currency: "Manx Pound", country: "Isle of Man", flag: "https://flagcdn.com/im.svg" },
  "INR": { currency: "Indian Rupee", country: "India", flag: "https://flagcdn.com/in.svg" },
  "IQD": { currency: "Iraqi Dinar", country: "Iraq", flag: "https://flagcdn.com/iq.svg" },
  "IRR": { currency: "Iranian Rial", country: "Iran", flag: "https://flagcdn.com/ir.svg" },
  "ISK": { currency: "Icelandic Króna", country: "Iceland", flag: "https://flagcdn.com/is.svg" },
  "JEP": { currency: "Jersey Pound", country: "Jersey", flag: "https://flagcdn.com/je.svg" },
  "JMD": { currency: "Jamaican Dollar", country: "Jamaica", flag: "https://flagcdn.com/jm.svg" },
  "JOD": { currency: "Jordanian Dinar", country: "Jordan", flag: "https://flagcdn.com/jo.svg" },
  "JPY": { currency: "Japanese Yen", country: "Japan", flag: "https://flagcdn.com/jp.svg" },
  "KES": { currency: "Kenyan Shilling", country: "Kenya", flag: "https://flagcdn.com/ke.svg" },
  "KGS": { currency: "Kyrgyzstani Som", country: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg" },
  "KHR": { currency: "Cambodian Riel", country: "Cambodia", flag: "https://flagcdn.com/kh.svg" },
  "KID": { currency: "Kiribati Dollar", country: "Kiribati", flag: "https://flagcdn.com/ki.svg" },
  "KMF": { currency: "Comorian Franc", country: "Comoros", flag: "https://flagcdn.com/km.svg" },
  "KRW": { currency: "South Korean Won", country: "South Korea", flag: "https://flagcdn.com/kr.svg" },
  "KWD": { currency: "Kuwaiti Dinar", country: "Kuwait", flag: "https://flagcdn.com/kw.svg" },
  "KYD": { currency: "Cayman Islands Dollar", country: "Cayman Islands", flag: "https://flagcdn.com/ky.svg" },
  "KZT": { currency: "Kazakhstani Tenge", country: "Kazakhstan", flag: "https://flagcdn.com/kz.svg" },
  "LAK": { currency: "Lao Kip", country: "Laos", flag: "https://flagcdn.com/la.svg" },
  "LBP": { currency: "Lebanese Pound", country: "Lebanon", flag: "https://flagcdn.com/lb.svg" },
  "LKR": { currency: "Sri Lanka Rupee", country: "Sri Lanka", flag: "https://flagcdn.com/lk.svg" },
  "LRD": { currency: "Liberian Dollar", country: "Liberia", flag: "https://flagcdn.com/lr.svg" },
  "LSL": { currency: "Lesotho Loti", country: "Lesotho", flag: "https://flagcdn.com/ls.svg" },
  "LYD": { currency: "Libyan Dinar", country: "Libya", flag: "https://flagcdn.com/ly.svg" },
  "MAD": { currency: "Moroccan Dirham", country: "Morocco", flag: "https://flagcdn.com/ma.svg" },
  "MDL": { currency: "Moldovan Leu", country: "Moldova", flag: "https://flagcdn.com/md.svg" },
  "MGA": { currency: "Malagasy Ariary", country: "Madagascar", flag: "https://flagcdn.com/mg.svg" },
  "MKD": { currency: "Macedonian Denar", country: "North Macedonia", flag: "https://flagcdn.com/mk.svg" },
  "MMK": { currency: "Myanma Kyat", country: "Myanmar", flag: "https://flagcdn.com/mm.svg" },
  "MNT": { currency: "Mongolian Tögrög", country: "Mongolia", flag: "https://flagcdn.com/mn.svg" },
  "MOP": { currency: "Macanese Pataca", country: "Macau", flag: "https://flagcdn.com/mo.svg" },
  "MRU": { currency: "Mauritanian Ouguiya", country: "Mauritania", flag: "https://flagcdn.com/mr.svg" },
  "MUR": { currency: "Mauritian Rupee", country: "Mauritius", flag: "https://flagcdn.com/mu.svg" },
  "MVR": { currency: "Maldivian Rufiyaa", country: "Maldives", flag: "https://flagcdn.com/mv.svg" },
  "MWK": { currency: "Malawian Kwacha", country: "Malawi", flag: "https://flagcdn.com/mw.svg" },
  "MXN": { currency: "Mexican Peso", country: "Mexico", flag: "https://flagcdn.com/mx.svg" },
  "MYR": { currency: "Malaysian Ringgit", country: "Malaysia", flag: "https://flagcdn.com/my.svg" },
  "MZN": { currency: "Mozambican Metical", country: "Mozambique", flag: "https://flagcdn.com/mz.svg" },
  "NAD": { currency: "Namibian Dollar", country: "Namibia", flag: "https://flagcdn.com/na.svg" },
  "NGN": { currency: "Nigerian Naira", country: "Nigeria", flag: "https://flagcdn.com/ng.svg" },
  "NIO": { currency: "Nicaraguan Córdoba", country: "Nicaragua", flag: "https://flagcdn.com/ni.svg" },
  "NOK": { currency: "Norwegian Krone", country: "Norway", flag: "https://flagcdn.com/no.svg" },
  "NPR": { currency: "Nepalese Rupee", country: "Nepal", flag: "https://flagcdn.com/np.svg" },
  "NZD": { currency: "New Zealand Dollar", country: "New Zealand", flag: "https://flagcdn.com/nz.svg" },
  "OMR": { currency: "Omani Rial", country: "Oman", flag: "https://flagcdn.com/om.svg" },
  "PAB": { currency: "Panamanian Balboa", country: "Panama", flag: "https://flagcdn.com/pa.svg" },
  "PEN": { currency: "Peruvian Sol", country: "Peru", flag: "https://flagcdn.com/pe.svg" },
  "PGK": { currency: "Papua New Guinean Kina", country: "Papua New Guinea", flag: "https://flagcdn.com/pg.svg" },
  "PHP": { currency: "Philippine Peso", country: "Philippines", flag: "https://flagcdn.com/ph.svg" },
  "PKR": { currency: "Pakistani Rupee", country: "Pakistan", flag: "https://flagcdn.com/pk.svg" },
  "PLN": { currency: "Polish Złoty", country: "Poland", flag: "https://flagcdn.com/pl.svg" },
  "PYG": { currency: "Paraguayan Guaraní", country: "Paraguay", flag: "https://flagcdn.com/py.svg" },
  "QAR": { currency: "Qatari Riyal", country: "Qatar", flag: "https://flagcdn.com/qa.svg" },
  "RON": { currency: "Romanian Leu", country: "Romania", flag: "https://flagcdn.com/ro.svg" },
  "RSD": { currency: "Serbian Dinar", country: "Serbia", flag: "https://flagcdn.com/rs.svg" },
  "RUB": { currency: "Russian Ruble", country: "Russia", flag: "https://flagcdn.com/ru.svg" },
  "RWF": { currency: "Rwandan Franc", country: "Rwanda", flag: "https://flagcdn.com/rw.svg" },
  "SAR": { currency: "Saudi Riyal", country: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg" },
  "SBD": { currency: "Solomon Islands Dollar", country: "Solomon Islands", flag: "https://flagcdn.com/sb.svg" },
  "SCR": { currency: "Seychellois Rupee", country: "Seychelles", flag: "https://flagcdn.com/sc.svg" },
  "SDG": { currency: "Sudanese Pound", country: "Sudan", flag: "https://flagcdn.com/sd.svg" },
  "SEK": { currency: "Swedish Krona", country: "Sweden", flag: "https://flagcdn.com/se.svg" },
  "SGD": { currency: "Singapore Dollar", country: "Singapore", flag: "https://flagcdn.com/sg.svg" },
  "SHP": { currency: "Saint Helena Pound", country: "Saint Helena", flag: "https://flagcdn.com/sh.svg" },
  "SLE": { currency: "Sierra Leonean Leone New", country: "Sierra Leone New", flag: "https://flagcdn.com/sl.svg" },
  "SLL": { currency: "Sierra Leonean Leone", country: "Sierra Leone", flag: "https://flagcdn.com/sl.svg" },
  "SOS": { currency: "Somali Shilling", country: "Somalia", flag: "https://flagcdn.com/so.svg" },
  "SRD": { currency: "Surinamese Dollar", country: "Suriname", flag: "https://flagcdn.com/sr.svg" },
  "SSP": { currency: "South Sudanese Pound", country: "South Sudan", flag: "https://flagcdn.com/ss.svg" },
  "STN": { currency: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe", flag: "https://flagcdn.com/st.svg" },
  "SYP": { currency: "Syrian Pound", country: "Syria", flag: "https://flagcdn.com/sy.svg" },
  "SZL": { currency: "Swazi Lilangeni", country: "Eswatini", flag: "https://flagcdn.com/sz.svg" },
  "THB": { currency: "Thai Baht", country: "Thailand", flag: "https://flagcdn.com/th.svg" },
  "TJS": { currency: "Tajikistani Somoni", country: "Tajikistan", flag: "https://flagcdn.com/tj.svg" },
  "TMT": { currency: "Turkmenistan Manat", country: "Turkmenistan", flag: "https://flagcdn.com/tm.svg" },
  "TND": { currency: "Tunisian Dinar", country: "Tunisia", flag: "https://flagcdn.com/tn.svg" },
  "TOP": { currency: "Tongan Paʻanga", country: "Tonga", flag: "https://flagcdn.com/to.svg" },
  "TRY": { currency: "Turkish Lira", country: "Turkey", flag: "https://flagcdn.com/tr.svg" },
  "TTD": { currency: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago", flag: "https://flagcdn.com/tt.svg" },
  "TVD": { currency: "Tuvaluan Dollar", country: "Tuvalu", flag: "https://flagcdn.com/tv.svg" },
  "TWD": { currency: "New Taiwan Dollar", country: "Taiwan", flag: "https://flagcdn.com/tw.svg" },
  "TZS": { currency: "Tanzanian Shilling", country: "Tanzania", flag: "https://flagcdn.com/tz.svg" },
  "UAH": { currency: "Ukrainian Hryvnia", country: "Ukraine", flag: "https://flagcdn.com/ua.svg" },
  "UGX": { currency: "Ugandan Shilling", country: "Uganda", flag: "https://flagcdn.com/ug.svg" },
  "USD": { currency: "United States Dollar", country: "United States", flag: "https://flagcdn.com/us.svg" },
  "UYU": { currency: "Uruguayan Peso", country: "Uruguay", flag: "https://flagcdn.com/uy.svg" },
  "UZS": { currency: "Uzbekistani Som", country: "Uzbekistan", flag: "https://flagcdn.com/uz.svg" },
  "VES": { currency: "Venezuelan Bolívar", country: "Venezuela", flag: "https://flagcdn.com/ve.svg" },
  "VND": { currency: "Vietnamese Dong", country: "Vietnam", flag: "https://flagcdn.com/vn.svg" },
  "VUV": { currency: "Vanuatu Vatu", country: "Vanuatu", flag: "https://flagcdn.com/vu.svg" },
  "WST": { currency: "Samoan Tala", country: "Samoa", flag: "https://flagcdn.com/ws.svg" },
  "XAF": { currency: "Central African CFA Franc", country: "Central African CFA", flag: "https://flagcdn.com/cf.svg" },
  "XCD": { currency: "East Caribbean Dollar", country: "East Caribbean", flag: "https://flagcdn.com/ag.svg" },
  "XCG": { currency: "The Carribean Guilder", country: "Caribbean Guilder", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/No_flag.svg/2560px-No_flag.svg.png" },
  "XDR": { currency: "Special Drawing Rights", country: "Special Drawing Rights", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/No_flag.svg/2560px-No_flag.svg.png" },
  "XOF": { currency: "West African CFA Franc", country: "West African CFA", flag: "https://flagcdn.com/bf.svg" },
  "XPF": { currency: "CFP Franc", country: "French Polynesia", flag: "https://flagcdn.com/pf.svg" },
  "YER": { currency: "Yemeni Rial", country: "Yemen", flag: "https://flagcdn.com/ye.svg" },
  "ZAR": { currency: "South African Rand", country: "South Africa", flag: "https://flagcdn.com/za.svg" },
  "ZMW": { currency: "Zambian Kwacha", country: "Zambia", flag: "https://flagcdn.com/zm.svg" },
  "ZWL": { currency: "Zimbabwean Dollar", country: "Zimbabwe", flag: "https://flagcdn.com/zw.svg" }
}
